[package]
name = "tcn_client"
version = "0.1.0"
authors = ["theseriousadult <jack@gallabytes.com>, ivanschuetz <ivanhp978@gmail.com>"]
edition = "2018"

[dependencies]
persy = "0.9"
once_cell = "1.3.1"

[dependencies.tcn]
git = "https://github.com/TCNCoalition/TCN.git"
branch = "main"
