# cbindgen --config cbindgen.toml --crate coepi_core --output ./src/ios/c_headers/coepicore.h

# Documentation:
# https://github.com/eqrion/cbindgen/blob/master/docs.md#cbindgentoml

language = "C"
sys_includes = ["CoreFoundation/CoreFoundation.h"]
no_includes = true

[defines]
"target_os=android" = "TARGET_OS_ANDROID"
"target_os = ios" = "TARGET_OS_IOS"
"target_os = macos" = "TARGET_OS_MACOS"