name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: ./android/core

jobs:
  instrumented_tests:
    name: Run Instrumented Tests
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest --stacktrace
      - name: Instrumented tests results
        uses: actions/upload-artifact@v2
        with:
          name: instrumented-tests-results
          path: app/build/reports/androidTests/connected/index.html

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: ./gradlew test --stacktrace
      - name: Unit tests results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html
